### ISSUE TITLE
Doc Bug in release notes

### ISSUE THREAD

**Issue by vanegi** [AdobeDocs/experience-manager-64.en#96] opened 2020-06-30 08:38 UTC
Issue in help/release-notes/sp-release-notes.md

It is highlighted that "Updated the jQuery version bundled in ContextHub to 3.4.1". But as part of GRANITE-19902 | NPR-28397, the jQuery version is updated to 3.2.1. 

Verified under /libs/granite/contexthub/dependencies/jquery and the correct version is updated to 3.2.1.

**Comment by anujkapo** [comment] 2020-06-30 08:52
Thanks, @vanegi  for reporting the issue. We'll look into it.

**Comment by aheim0** [comment] 2020-06-30 10:26
CQDOC-16405

**Comment by anujkapo** [comment] 2020-06-30 13:13
The issue is fixed with the following git commit:
https://git.corp.adobe.com/AdobeDocs/experience-manager-64.en/pull/944/commits/98d52be43b1668b0f16ae18fc82402acc1058a38

**Closed** 2020-07-05 11:03 UTC
Labels: bug
